POST http://localhost:8080/api/v1/spread
Content-Type: application/json
X-ROOM-ID: abc
X-USER-ID: hello.gutentag

{"request_amount" :  60000, "request_receiver_count" :  5}

###

GET http://localhost:8080/api/v1/getmoney/0de
Content-Type: application/json
X-ROOM-ID: abc
X-USER-ID: pony.tail


###

GET http://localhost:8080/api/v1/details/0de
Content-Type: application/json
X-ROOM-ID: abc
X-USER-ID: hello.gutentag
